[package]
name = "worm"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = { version = "0.26.3", features = ["all-widgets"] }
anyhow = "1.0.86"
color-eyre = "0.6.3"
rand = "0.8.5"
itertools = "0.13.0"
